/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

/**
 *
 * @author semimat19
 */
public class BoardVisuals extends javax.swing.JPanel {
    private Tictactoe parent;
    /**
     * Creates new form BoardVisuals
     */
    public BoardVisuals(Tictactoe parent) {
        initComponents();
        this.parent = parent;
        this.setSize(600, 600);

        // add all the buttons!
        int index = 0;
        for (int boardRow = 0; boardRow < 3 ; boardRow++) {
            for (int boardCol = 0; boardCol < 3; boardCol++) {
                for (int rows = 0; rows < 3; rows++) {
                    for (int cols = 0; cols < 3; cols++) {
                        MyButton btn = new MyButton(index++);
                        this.add(btn);
                        btn.setText("X");
                        btn.setSize(40, 40);

                        // TODO - set button position
                        btn.setLocation(boardCol * 130 + 40 * cols, boardRow * 130 + 40 * rows);
                        btn.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                myButtonActionPerformed(evt);
                            }
                        });
                        btn.setVisible(true);
                    }
                }            
            }
        }
    }

    public void myButtonActionPerformed(java.awt.event.ActionEvent evt) {
        MyButton btn = (MyButton)evt.getSource();
        parent.buttonClicked(btn.getIndex());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
