/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

import java.awt.Color;

/**
 *
 * @author Matt
 */
public class MenuPanel extends javax.swing.JPanel {

    private Tictactoe parent;

    /**
     * Creates new form MenuPanel
     */
    public MenuPanel(Tictactoe parent) {
        initComponents();
        this.parent = parent;
        this.setBackground(Color.gray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        onePlayerButton = new javax.swing.JButton();
        twoPlayerButton = new javax.swing.JButton();

        onePlayerButton.setText("One-Player");
        onePlayerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onePlayerButtonMouseClicked(evt);
            }
        });

        twoPlayerButton.setText("Two-Player");
        twoPlayerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twoPlayerButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(twoPlayerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(onePlayerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap(350, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(onePlayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200)
                .addComponent(twoPlayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void onePlayerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onePlayerButtonMouseClicked
        // TODO add your handling code here:
        parent.showBoard();
        parent.setOnePlayer(true);
    }//GEN-LAST:event_onePlayerButtonMouseClicked

    private void twoPlayerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoPlayerButtonMouseClicked
        // TODO add your handling code here:
        parent.showBoard();
        parent.setOnePlayer(false);
    }//GEN-LAST:event_twoPlayerButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton onePlayerButton;
    private javax.swing.JButton twoPlayerButton;
    // End of variables declaration//GEN-END:variables
}
